### production

# workflows/hugo.yaml の --baseURL "${{ steps.pages.outputs.base_url }}/" で定義される
# baseURL: "https://14katsumix.github.io/"
# baseURL: "https://14jcjc.github.io/tech/"
# baseURL: "https://14jcjc.github.io/"
# baseURL: "https://katsu-ds-lab.com/"

# Include drafts when building.
buildDrafts: false
# buildDrafts: true

# enableRobotsTXT: true # robots.txt の生成を有効にする
enableRobotsTXT: false

# disableKinds: true # sitemap.xml の生成を有効にする
disableKinds: 
  - sitemap

services:
  googleAnalytics:
    ID: G-RWR5N47BDG
    # ID: G-GLB0HGKER4
  # Change it to your Disqus shortname before using
  # disqus:
  #   shortname: your-disqus-shortname
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

# permalinks を設定すると, パンクズリストがきちんと表示されなくなる.
#-> /themes/PaperMod/layouts/partials/breadcrumbs.html を修正することで解決.
#   https://github.com/adityatelange/hugo-PaperMod/issues/1585
permalinks:
  page:
    page: /:slug/
    # ds-drills: /ds-practice-drills/:sections[1:]/:slug/
    ds-drills: /ds-drills/:slug/
    dev: /dev/:slug/
    test: /test/:slug/
    # post: /p/:slug/
    # aaa: /aaa/:year/:month/:slug/
    # xxx: /xxx/:slug
  section:
    ds-drills: /ds-drills/:sections[last]/
    dev: /dev/:sections[last]/
    # ds-drills: /ds-practice-drills/:sections[1:]/
    # aaa: /aaa/:year/:month/
    # xxx: /xxx/:sections[1:]/

params:
  # (?) to enable google analytics, opengraph, twitter-cards and schema. 
  env: production
  mainSections:
    - "ds-drills"
    - dev
    - test
    # - post

### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
languages:
  ja:
    languageName: Japanese
    weight: 1
    params:
        sidebar:
            subtitle: "R と SQL で学ぶ、データ活用の実践スキル"
    menu:
      main:
        # - identifier: "katsu データサイエンスラボ"
        - identifier: "katsu DS Lab"
          name: Home
          url: /
          weight: -20
          params: 
            icon: home
        
        - identifier: About
          name: About
          url: /about
          weight: -10
          params:
            icon: user

        - identifier: "[R & SQL] 演習問題一覧"
          # name: "[R & SQL] データサイエンス実践ドリル"
          name: "R & SQL 演習問題一覧"
          url: "/ds-drills/drill-list"
          weight: 10
          params: 
            icon: question
        
        - identifier: "レビュー"
          name: レビュー
          url: "/categories/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC/"
          # url: "/ds100knocks-alpha/book-review/"
          weight: 20
          params: 
            icon: review

        - identifier: "Archives"
          name: Archives
        # - name: アーカイブ
          url: /archives
          weight: 40
          params: 
            icon: archives
        
        - identifier: Search
          name: Search
        # - name: 検索
          url: /search
          weight: 50
          params: 
            icon: search
        # - name: Links
        #   url: /links
        #   weight: 60
        #   params:
        #       icon: link

  # en:
  #   languageName: English
  #   weight: 2
  #   params:
  #       sidebar:
  #           subtitle: Real-World Data Mastery with R & SQL
  #   menu:
  #     main:
  #       - identifier: "Katsu Data Science Lab"
  #         name: Home
  #         url: /en/
  #         weight: -20
  #         params: 
  #           icon: home
        
  #       - identifier: About
  #         name: About
  #         url: /en/about
  #         weight: -10
  #         params:
  #           icon: user

  #       - identifier: "[R & SQL] データサイエンス100本ノック＋α - 演習問題一覧"
  #         # name: "[R & SQL] Data Science Practical Drill"
  #         name: "[R & SQL] Data Science Practice Drills"
  #         url: "/en/ds100knocks-alpha/q-list"
  #         weight: 10
  #         params: 
  #           icon: question
        
  #       - identifier: "レビュー"
  #         name: Review
  #         url: "/en/categories/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC/"
  #         # url: "/ds100knocks-alpha/book-review/"
  #         weight: 20
  #         params: 
  #           icon: review

  #       - identifier: "Archives"
  #         name: Archives
  #       # - name: アーカイブ
  #         url: /en/archives
  #         weight: 40
  #         params: 
  #           icon: archives
        
  #       - identifier: Search
  #         name: Search
  #       # - name: 検索
  #         url: /en/search
  #         weight: 50
  #         params: 
  #           icon: search

module:
  mounts:
  - excludeFiles: 
      - post
      # - test
      # - ds-drills/test
      # - categories
      # - test/books/**
    source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
